name: "Planets Positions Addon"
description: "Add-on that encapsulates the planets positions node server"
version: "0.9.1"
slug: "planets"
url: "https://github.com/philpownall/planets-rest-api"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  3100/tcp: 3100
options:
  latitude: 44.2307
  longitude: -76.4813
schema:
  latitude: float
  longitude: float
